name: Build checks

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.1
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2.1.5
      - name: Run Build
        run: ./gradlew assembleDebug
